name: utulogin
description: A Flutter project which lets you login to your utu wifi and sis login automatically.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+0

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  webview_flutter: ^4.2.0
  flutter_inappwebview: ^5.7.2+3
  shared_preferences: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  version: ^3.0.2
  package_info_plus: ^3.1.2
  http: ^0.13.6
  html: ^0.15.3
  flutter_shortcuts: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/ic_sis.xml
  #   - assets/ic_wifi.xml